"""Elijah add transcript col to transcripts segmented.

Revision ID: 1e475373c285
Revises: 5bcf3df5bdf3
Create Date: 2024-04-25 10:42:33.596054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e475373c285'
down_revision: Union[str, None] = '5bcf3df5bdf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts_segmented', sa.Column('transcript', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts_segmented', 'transcript')
    # ### end Alembic commands ###
