"""Elijah Added transcription table.

Revision ID: 239551ec25eb
Revises: 97799eab9aca
Create Date: 2024-04-22 16:20:45.393223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239551ec25eb'
down_revision: Union[str, None] = '97799eab9aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos_transcribed',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('transcribed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos_transcribed')
    # ### end Alembic commands ###
