"""Elijah split video segmented and transcript segmented.

Revision ID: 5bcf3df5bdf3
Revises: c49afada17b3
Create Date: 2024-04-25 10:31:22.274621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bcf3df5bdf3'
down_revision: Union[str, None] = 'c49afada17b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts_segmented',
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('earliest_start_time', sa.Integer(), nullable=True),
    sa.Column('latest_end_time', sa.Float(), nullable=True),
    sa.Column('start_index', sa.Integer(), nullable=True),
    sa.Column('end_index', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('words', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_table('videos_segmented',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('segmented_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.drop_table('original_videos_segmented')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('original_videos_segmented',
    sa.Column('segment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('earliest_start_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latest_end_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('words', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('segment_id', name='original_videos_segmented_pkey')
    )
    op.drop_table('videos_segmented')
    op.drop_table('transcripts_segmented')
    # ### end Alembic commands ###
