"""Elijah added segment vector upload.

Revision ID: 66bb44933c13
Revises: 86d25a0e4b92
Create Date: 2024-04-26 10:53:19.114833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66bb44933c13'
down_revision: Union[str, None] = '86d25a0e4b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts_segment_vectors_stored',
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.alter_column('channels_downloaded', 'channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('channels_downloaded', 'channel_link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('channels_downloaded', 'channel_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels_downloaded', 'channel_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('channels_downloaded', 'channel_link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('channels_downloaded', 'channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_table('transcripts_segment_vectors_stored')
    # ### end Alembic commands ###
