"""Elijah added videos vectors stored table.

Revision ID: 7d32d205c618
Revises: 66bb44933c13
Create Date: 2024-04-26 11:43:58.072946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d32d205c618'
down_revision: Union[str, None] = '66bb44933c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos_vectors_stored',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos_vectors_stored')
    # ### end Alembic commands ###
