"""Elijah added transcripts raw table.

Revision ID: 97799eab9aca
Revises: e0bc312f3fb9
Create Date: 2024-04-22 13:56:26.366811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97799eab9aca'
down_revision: Union[str, None] = 'e0bc312f3fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts_raw',
    sa.Column('transcript_id', sa.String(), nullable=False),
    sa.Column('time_start_ms', sa.Integer(), nullable=True),
    sa.Column('d_duration_ms', sa.Integer(), nullable=True),
    sa.Column('segs', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('transcript_id')
    )
    op.alter_column('channels_downloaded', 'channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('channels_downloaded', 'channel_link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('channels_downloaded', 'channel_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels_downloaded', 'channel_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('channels_downloaded', 'channel_link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('channels_downloaded', 'channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_table('transcripts_raw')
    # ### end Alembic commands ###
