"""Elijah - reset tables.

Revision ID: f4f984fc8de6
Revises: 7d32d205c618
Create Date: 2024-04-30 13:52:40.232595

"""
from typing import Sequence, Union
from sqlalchemy import text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f984fc8de6'
down_revision: Union[str, None] = '7d32d205c618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels_downloaded', 'channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('channels_downloaded', 'channel_link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('channels_downloaded', 'channel_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('channels_downloaded', 'date_added',
                    existing_type=sa.TEXT(),
                    type_=sa.TIMESTAMP(),
                    existing_nullable=True,
                    # Add the USING clause to specify conversion
                    postgresql_using='date_added::timestamp without time zone')
    op.alter_column('embeddings_segment', 'segment_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('embeddings_segment', 'video_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('embeddings_segment', 'embedding', type_=sa.LargeBinary(), postgresql_using='embedding::bytea')
    op.alter_column('transcripts_segment_embedded', 'segment_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('transcripts_segment_embedded', 'video_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'segment_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('transcripts_segmented', 'earliest_start_time',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'start_index',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'end_index',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'video_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'index',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'words',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'transcript',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'video_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('videos_cleaned', 'channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'channel_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'publish_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'width',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'height',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'aspect_ratio',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'projection',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('videos_cleaned', 'download_link')
    op.alter_column('videos_segmented', 'video_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos_segmented', 'video_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('videos_cleaned', sa.Column('download_link', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('videos_cleaned', 'projection',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'aspect_ratio',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'height',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'width',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'publish_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'channel_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('videos_cleaned', 'video_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('transcripts_segmented', 'transcript',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'words',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'index',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'video_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'end_index',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'start_index',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'earliest_start_time',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('transcripts_segmented', 'segment_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('transcripts_segment_embedded', 'video_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transcripts_segment_embedded', 'segment_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('embeddings_segment', 'embedding',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('embeddings_segment', 'video_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('embeddings_segment', 'segment_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('channels_downloaded', 'date_added',
               existing_type=sa.TIMESTAMP(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('channels_downloaded', 'channel_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('channels_downloaded', 'channel_link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('channels_downloaded', 'channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
